In [16]:
import pandas as pd

df = pd.read_csv("../data/processed/nba_games_features.csv")

df.head()

,HOME_GAME_ID,HOME_GAME_DATE,HOME_TEAM_NAME,AWAY_TEAM_NAME,home_team_win,home_court,win_last5_diff,win_last10_diff,PTS_last5_diff,PTS_last10_diff,...,FT_PCT_last10_diff,REB_last5_diff,REB_last10_diff,AST_last5_diff,AST_last10_diff,TOV_last5_diff,TOV_last10_diff,rest_days_diff,back_to_back_diff,home_away_form_diff
0,12100031,2021-10-08,Golden State Warriors,Los Angeles Lakers,1,1,1.0,1.0,18.5,18.5,...,0.0400,4.0,4.0,9.0,9.0,-2.0,-2.0,0.0,0,1.0
1,12100027,2021-10-08,Chicago Bulls,New Orleans Pelicans,1,1,0.5,0.5,22.0,22.0,...,-0.0155,4.0,4.0,11.5,11.5,-6.5,-6.5,1.0,0,1.0
2,12100029,2021-10-08,San Antonio Spurs,Miami Heat,0,1,-0.5,-0.5,-11.0,-11.0,...,-0.0220,13.0,13.0,-6.0,-6.0,-4.5,-4.5,1.0,-1,0.0
3,12100034,2021-10-09,Memphis Grizzlies,Atlanta Hawks,0,1,1.0,1.0,10.0,10.0,...,-0.1075,16.0,16.0,1.0,1.0,2.0,2.0,-1.0,0,1.0
4,12100032,2021-10-09,Boston Celtics,Toronto Raptors,1,1,0.5,0.5,-20.0,-20.0,...,0.1080,6.0,6.0,-8.0,-8.0,-4.0,-4.0,3.0,0,1.0

In [17]:
df.shape
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 5531 entries, 0 to 5530
Data columns (total 31 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   HOME_GAME_ID                   5531 non-null   int64
 1   HOME_GAME_DATE                 5531 non-null   str
 2   HOME_TEAM_NAME                 5531 non-null   str
 3   AWAY_TEAM_NAME                 5531 non-null   str
 4   home_team_win                  5531 non-null   int64
 5   home_court                     5531 non-null   int64
 6   win_last5_diff                 5531 non-null   float64
 7   win_last10_diff                5531 non-null   float64
 8   PTS_last5_diff                 5531 non-null   float64
 9   PTS_last10_diff                5531 non-null   float64
 10  PTS_ALLOWED_last5_diff         5531 non-null   float64
 11  PTS_ALLOWED_last10_diff        5531 non-null   float64
 12  point_diff_last5_diff          5531 non-null   float64
 13  point_diff_last10_diff         5531 non-null   float64
 14  net_rating_simple_last5_diff   5531 non-null   float64
 15  net_rating_simple_last10_diff  5531 non-null   float64
 16  FG_PCT_last5_diff              5531 non-null   float64
 17  FG_PCT_last10_diff             5531 non-null   float64
 18  FG3_PCT_last5_diff             5531 non-null   float64
 19  FG3_PCT_last10_diff            5531 non-null   float64
 20  FT_PCT_last5_diff              5531 non-null   float64
 21  FT_PCT_last10_diff             5531 non-null   float64
 22  REB_last5_diff                 5531 non-null   float64
 23  REB_last10_diff                5531 non-null   float64
 24  AST_last5_diff                 5531 non-null   float64
 25  AST_last10_diff                5531 non-null   float64
 26  TOV_last5_diff                 5531 non-null   float64
 27  TOV_last10_diff                5531 non-null   float64
 28  rest_days_diff                 5531 non-null   float64
 29  back_to_back_diff              5531 non-null   int64
 30  home_away_form_diff            5531 non-null   float64
dtypes: float64(24), int64(4), str(3)
memory usage: 1.5 MB

,HOME_GAME_ID,home_team_win,home_court,win_last5_diff,win_last10_diff,PTS_last5_diff,PTS_last10_diff,PTS_ALLOWED_last5_diff,PTS_ALLOWED_last10_diff,point_diff_last5_diff,...,FT_PCT_last10_diff,REB_last5_diff,REB_last10_diff,AST_last5_diff,AST_last10_diff,TOV_last5_diff,TOV_last10_diff,rest_days_diff,back_to_back_diff,home_away_form_diff
count,5.531000e+03,5531.000000,5531.0,5531.000000,5531.000000,5531.000000,5531.000000,5531.000000,5531.000000,5531.000000,...,5531.000000,5531.000000,5531.000000,5531.000000,5531.000000,5531.000000,5531.000000,5531.000000,5531.000000,5531.000000
mean,2.317013e+07,0.554511,1.0,-0.001811,-0.002971,-0.221919,-0.133261,-0.078340,-0.064874,-0.143579,...,-0.000084,0.024968,0.030753,-0.065742,-0.053362,-0.039719,-0.006464,-0.080636,-0.030555,0.116552
std,5.683555e+06,0.497065,0.0,0.371615,0.293229,9.398789,7.695666,9.646237,7.859865,12.237461,...,0.055829,4.965656,3.942473,4.022629,3.450181,2.748690,2.223378,12.890540,0.476165,0.371648
min,1.210003e+07,0.000000,1.0,-1.000000,-1.000000,-34.400000,-29.300000,-47.800000,-39.800000,-52.200000,...,-0.224000,-21.200000,-14.800000,-16.200000,-12.000000,-10.666667,-12.400000,-365.000000,-1.000000,-1.000000
25%,2.210114e+07,0.000000,1.0,-0.200000,-0.200000,-6.400000,-5.300000,-6.600000,-5.300000,-8.000000,...,-0.039350,-3.200000,-2.500000,-2.800000,-2.400000,-1.800000,-1.500000,0.000000,0.000000,-0.200000
50%,2.230006e+07,1.000000,1.0,0.000000,0.000000,-0.200000,-0.200000,-0.200000,0.000000,-0.200000,...,0.000000,0.000000,0.000000,0.000000,-0.100000,0.000000,0.000000,0.000000,0.000000,0.200000
75%,2.240021e+07,1.000000,1.0,0.200000,0.200000,5.800000,5.000000,6.400000,5.300000,8.000000,...,0.038550,3.400000,2.600000,2.600000,2.300000,1.800000,1.500000,1.000000,0.000000,0.400000
max,6.230000e+07,1.000000,1.0,1.000000,1.000000,48.400000,49.500000,34.400000,26.200000,70.000000,...,0.216750,19.000000,18.000000,13.800000,12.833333,12.200000,12.000000,364.000000,1.000000,1.000000

In [ ]:
#creates baseline for model to beat
#computes percentage of home team wins
df["home_team_win"].value_counts(normalize=True)

home_team_win
1    0.555716
0    0.444284
Name: proportion, dtype: float64

In [18]:
corr = df.corr(numeric_only=True)

corr["home_team_win"]\
    .sort_values(ascending=False)\
    .head(25)

home_team_win                    1.000000
point_diff_last10_diff           0.273156
net_rating_simple_last10_diff    0.273156
win_last10_diff                  0.240784
point_diff_last5_diff            0.239120
net_rating_simple_last5_diff     0.239120
home_away_form_diff              0.212076
win_last5_diff                   0.205228
PTS_last10_diff                  0.174469
FG_PCT_last10_diff               0.168227
PTS_last5_diff                   0.163271
FG_PCT_last5_diff                0.146461
FG3_PCT_last10_diff              0.125008
AST_last10_diff                  0.103572
FG3_PCT_last5_diff               0.103137
AST_last5_diff                   0.102190
FT_PCT_last10_diff               0.064966
REB_last5_diff                   0.062012
REB_last10_diff                  0.055282
FT_PCT_last5_diff                0.046921
HOME_GAME_ID                     0.019260
rest_days_diff                  -0.006990
back_to_back_diff               -0.074330
TOV_last5_diff                  -0.106282
PTS_ALLOWED_last5_diff          -0.144271
Name: home_team_win, dtype: float64

In [15]:
df.columns.tolist()

['HOME_GAME_ID',
 'HOME_GAME_DATE',
 'HOME_TEAM_NAME',
 'AWAY_TEAM_NAME',
 'home_team_win',
 'home_court',
 'HOME_point_diff',
 'AWAY_point_diff',
 'win_last5_diff',
 'win_last10_diff',
 'PTS_last5_diff',
 'PTS_last10_diff',
 'PTS_ALLOWED_last5_diff',
 'PTS_ALLOWED_last10_diff',
 'point_diff_last5_diff',
 'point_diff_last10_diff',
 'net_rating_simple_last5_diff',
 'net_rating_simple_last10_diff',
 'FG_PCT_last5_diff',
 'FG_PCT_last10_diff',
 'FG3_PCT_last5_diff',
 'FG3_PCT_last10_diff',
 'FT_PCT_last5_diff',
 'FT_PCT_last10_diff',
 'REB_last5_diff',
 'REB_last10_diff',
 'AST_last5_diff',
 'AST_last10_diff',
 'TOV_last5_diff',
 'TOV_last10_diff',
 'rest_days_diff',
 'back_to_back_diff',
 'home_away_form_diff']